# For available configuration options, see:
#   https://github.com/testdouble/standard
ruby_version: 2.6

ignore:
  - 'lib/**/*':
    - Layout/ExtraSpacing
    - Layout/HashAlignment
  - 'spec/**/*':
    - Layout/ExtraSpacing
    - Layout/HashAlignment
