# For available configuration options, see:
#   https://github.com/testdouble/standard
ruby_version: 2.7

ignore:
  - '**/*':
    - Layout/ExtraSpacing
    - Layout/HashAlignment
    - Layout/ArgumentAlignment
    - Style/EmptyCaseCondition
    - Style/RescueModifier
