# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra",      "~> 4.0"
gem "rackup",       "~> 2.1"
gem "webrick",      "~> 1.9"
gem "rack-contrib", "~> 2.4"
gem "linzer",       "~> 0.7.0.beta2"
