name: Ruby

on:
  push:
    branches:
      - '**'

  pull_request:

  schedule:
  - cron: "21 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          # - '3.0' Note: A separate job is needed for Ruby 3.0. See below.
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - head
        include:
          - ruby-version: head
          - allow-failure: true
      fail-fast: false

    continue-on-error: ${{ matrix.allow-failure == true }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run integration tests
      run: bundle exec rake integration
    - name: Run the default task
      run: bundle exec rake

  # To run linzer tests on Ruby 3.0 on Github Actions environment:
  # linzer RSA signing/verifying functionality depends on openssl gem >= 3.0.
  # However, Ruby 3.0 by default is linked with OpenSSL 1.1 and there is no
  # convenient way to override it.
  #
  # As result, Ruby 3.0 is built in this way to avoid the precompiled version
  # available in Github Actions that's linked with OpenSSL 1.1 library and
  # will not pickup OpenSSL 3.0 system library, even when openssl gem >= 3.0
  # is bundled with your library.
  #
  # Example: https://gist.github.com/yob/08d53a003181aa0fcce9812b1b533870
  #
  # A better approach and/or a PR to fix this kludge is more than welcome.
  build-v3_0:
    runs-on: ubuntu-latest
    name: Ruby 3.0
    steps:
    - uses: actions/checkout@v4
    - name: Install Ruby 3.0 dependencies
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt-get -o Acquire::Retries=3 update
        sudo apt-get -o Acquire::Retries=3 build-dep ruby --yes
        sudo apt-get -o Acquire::Retries=3 install git curl libssl-dev --yes
    - name: Install ruby-install script
      run: |
        cd `mktemp -d`
        git clone https://github.com/postmodern/ruby-install
        echo "$PWD/ruby-install/bin" >> $GITHUB_PATH
    - name: Build Ruby 3.0
      run: |
        ruby-install --update
        ruby-install 3.0.7
    - name: Install chruby script
      run: |
        cd `mktemp -d`
        git clone https://github.com/postmodern/chruby
        echo "$PWD/chruby/bin" >> $GITHUB_PATH
    - name: Ruby 3.0 quick test
      run: |
        chruby-exec 3.0.7 -- ruby -v
    - name: Install openssl 3.0 gem
      run: |
        curl -L -O https://rubygems.org/downloads/openssl-3.0.0.gem
        chruby-exec 3.0.7 -- gem install openssl-3.0.0.gem
        chruby-exec 3.0.7 -- ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
    - name: Install linzer dependencies
      run: |
        chruby-exec 3.0.7 -- bundle install
    - name: Run integration tests
      run: |
        chruby-exec 3.0.7 -- bundle exec rake integration
    - name: Run the default task
      run: |
        chruby-exec 3.0.7 -- bundle exec rake
